# --------
# Services
# --------

["socialnetwork/pkg/services/ComposePostService"]
redis_address       = "localhost"
redis_port          = 6381
region              = "europe-west3"
regions             = ["europe-west3", "us-central1"]

["socialnetwork/pkg/services/HomeTimelineService"]
redis_address       = "localhost"
redis_port          = 6382
region              = "europe-west3"

["socialnetwork/pkg/services/PostStorageService"]
mongodb_address     = "localhost"
memcached_address   = "localhost"
mongodb_port        = 27017
memcached_port      = 11212
region              = "europe-west3"

["socialnetwork/pkg/services/SocialGraphService"]
mongodb_address     = "localhost"
redis_address       = "localhost"
redis_port          = 6384
mongodb_port        = 27017
region              = "europe-west3"

["socialnetwork/pkg/services/UrlShortenService"]
mongodb_address     = "localhost"
memcached_address   = "localhost"
mongodb_port        = 27017
memcached_port      = 11213
region              = "europe-west3"

["socialnetwork/pkg/services/UserService"]
mongodb_address     = "localhost"
memcached_address   = "localhost"
mongodb_port        = 27017
memcached_port      = 11214
region              = "europe-west3"

["socialnetwork/pkg/services/UserMentionService"]
# uses UserService cache (memcached)
mongodb_address     = "localhost"
memcached_address   = "localhost"
mongodb_port        = 27017
memcached_port      = 11214
region              = "europe-west3"

["socialnetwork/pkg/services/UserTimelineService"]
mongodb_address     = "localhost"
redis_address       = "localhost"
mongodb_port        = 27017
redis_port          = 6383
region              = "europe-west3"

#["socialnetwork/pkg/services/WriteHomeTimelineService"]
#rabbitmq_address    = "localhost"
#mongodb_address     = "localhost"
#redis_address       = "localhost" #uses HomeTimelineService cache (redis)
#mongodb_port        = 27017
#redis_port          = 6382
#rabbitmq_port       = 5672
#num_workers         = 16
#region              = "europe-west3"

# WRITE HOME TIMELINE ACCESSES STORAGES IN "US"
["socialnetwork/pkg/services/WriteHomeTimelineService"]
redis_address       = "localhost" #uses HomeTimelineService cache (redis)
redis_port          = 6386
num_workers         = 16
region              = "us-central1"

["socialnetwork/pkg/services/MediaService"]
region              = "europe-west3"

["socialnetwork/pkg/services/TextService"]
region              = "europe-west3"

["socialnetwork/pkg/services/UniqueIdService"]
region              = "europe-west3"

# wrk2 api
["github.com/ServiceWeaver/weaver/Main"]
region              = "europe-west3"

# ----------
# Deployment
# ----------

[single]
listeners.wrk2 = {address = "127.0.0.1:9000"}
antipodeAgents.rabbitClientWriteHomeTL = {datastoreType = "RabbitMQ", host = "localhost", port = "5673", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientCompose = {datastoreType = "RabbitMQ", host = "localhost", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.mongoClientPostStorage = {datastoreType = "MongoDB", host = "localhost", port = "27017", datastore = "post-storage"}
antipodeAgents.mongoClientWriteHomeTL = {datastoreType = "MongoDB", host = "localhost", port = "27018", datastore = "post-storage"}

[multi]
listeners.wrk2 = {address = "127.0.0.1:9000"}
antipodeAgents.rabbitClientWriteHomeTL = {datastoreType = "RabbitMQ", host = "localhost", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.rabbitClientCompose = {datastoreType = "RabbitMQ", host = "localhost", port = "5672", user = "admin", password = "admin", datastore = "rabbitMQ", queue = "write-home-timeline"}
antipodeAgents.mongoClientPostStorage = {datastoreType = "MongoDB", host = "localhost", port = "27017", datastore = "post-storage"}
antipodeAgents.mongoClientWriteHomeTL = {datastoreType = "MongoDB", host = "localhost", port = "27018", datastore = "post-storage"}


[serviceweaver]
binary = "./socialnetwork"
name = "socialnetwork-eu"

[gke]
regions = ["europe-west3"]
listeners.wrk2 = {public_hostname = "weaver.dsb.socialnetwork.eu"}
